### ISSUE TITLE
Tasmota SML Script + Chart + PV.txt => Publish of consyear and yieldyear value incorrect

### ISSUE THREAD

**Issue by sparcisgone** [ottelo9/tasmota-sml-script#2]
Die Publish statements für die Jahreswerte sollten so aussehen:
	=>publish stat/%topic%/script/consyear %2(EnFrGrid-yval)%
	=>publish stat/%topic%/script/yieldyear %2(EnToGrid-yval2)%

Original sehen sie so aus und liefern dadruch keine korrekten Werte:
	;=>publish stat/%topic%/script/consyear %2(yval)%
	;=>publish stat/%topic%/script/yielyear %2(yval2)%

**Comment by ottelo9** [comment]
Danke für den Hinweis. Ich bin sowieso gerade am Script dran und update es demnächst.

**Comment by ottelo9** [comment]
Beim letzten Scriptupdate gefixt.
